# exec-once = waybar & hyprpaper & firefox

exec-once = echo "---------LOG---------" > hyprstart.log
exec-once = swww-daemon
#exec-once = waypaper --restore >> hyprstart.log
exec-once = /home/lauri/Documents/scripts/auto_swww
exec-once = systemctl --user start hyprpolkitagent >> hyprstart.log
exec-once = waybar >> hyprstart.log
# exec-once = ags run >> hyprstart.log
