-- Generated by nwg-displays on 2026-06-11 at 11:37:20. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2256x1504@60.0",
    position = "7580x1440",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@30.0",
    position = "7910x576",
    scale = 2.5
})
