# Multimedia Tagging
windowrule {
    name = tag multimedia_video
    match:class = ^([Mm]pv|vlc)$
}

# Settings Tagging
windowrule {
    name = tag settings
    match:class = ^(nm-applet|nm-connection-editor|blueman-manager|org.gnome.FileRoller)$
}

windowrule {
    name = tag settings
    match:class = ^(org.gnome.DiskUtility|wihotspot(-gui)?)$
}

# Viewer Tagging
windowrule {
    name = tag viewer
    match:class = ^(org.gnome.SystemMonitor)$
}

windowrule {
    name = tag viewer
    match:class = ^(org.gnome.Evince)$
}

windowrule {
    name = tag viewer
    match:class = ^(eog|org.gnome.Loupe)$
}
